# Generated by Django 3.2.22 on 2023-10-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_videoproxy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'Published video', 'verbose_name_plural': 'Published videos'},
        ),
    ]
